[package]
name = "metal-git"
version = "0.0.1"
authors = ["Yoichi Imai <sunnyone41@gmail.com>"]
build = "build.rs"

[lib]
name = "metal_git"
path = "src/main.rs"

[dependencies]
rustc-serialize = "0.3.24" # https://github.com/coeuvre/rust-2048/issues/30
git2 = "^0.14"
gtk = { version = "^0.15.1" }
gdk = "*"
glib = "*"
cairo = "*"
gio = "*"
#glib-sys = "*"
#gio-sys = "*"
#gobject-sys = "*"
#pango-sys = "*"
#cairo-sys = "*"
#gdk-sys = "*"
#gtk-sys = "*"

#libc = "0.2"

#
#[dependencies.cairo-rs]
#git = "https://github.com/gtk-rs/cairo"
#
#[dependencies.cairo-sys-rs]
#git = "https://github.com/gtk-rs/cairo"
#version = "0.3.0"
#
#[dependencies.gdk]
#git = "https://github.com/gtk-rs/gdk.git"
#
#[dependencies.gtk]
#git = "https://github.com/gtk-rs/gtk.git"
#features = ["v3_10"]
#
#[dependencies.pango]
#git = "https://github.com/gtk-rs/pango.git"
#
#[dependencies.gdk-pixbuf]
#git = "https://github.com/gtk-rs/gdk-pixbuf.git"
#
#[dependencies.glib]
#git = "https://github.com/gtk-rs/glib.git"
#
#[dependencies.gio]
#git = "https://github.com/gtk-rs/gio.git"
#
#[dependencies.gtk-sys]
#git = "https://github.com/gtk-rs/sys.git"
#path = "gtk-sys"
#
#[dependencies.pango-sys]
#git = "https://github.com/gtk-rs/sys.git"
#path = "pango-sys"
#
#[dependencies.gdk-sys]
#git = "https://github.com/gtk-rs/sys.git"
#path = "gdk-sys"
#
#[dependencies.glib-sys]
#git = "https://github.com/gtk-rs/sys.git"
#path = "glib-sys"
#
#[dependencies.gio-sys]
#git = "https://github.com/gtk-rs/sys.git"
#path = "gio-sys"
#
#[dependencies.gobject-sys]
#git = "https://github.com/gtk-rs/sys.git"
#path = "gobject-sys"

[dev-dependencies]
tempdir = "0.3"

